version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    logging:
      driver: "awslogs"
      options:
        awslogs-group: "/ecs/flask-app"
        awslogs-region: "ap-south-1"
        awslogs-stream-prefix: "flask-app"
